---
- hosts: localhost

  tasks:
    
  - name: Install plugin
    jenkins_plugin:  
      name: ccm
      url_username: "host_user"
      url_password: "host_pwd"
      url: "host_url"
       
  - name: Install plugin
    jenkins_plugin:  
      name: postgres
      url_username: "host_user"
      url_password: "host_pwd"
      url: "host_url"
       
  - name: Install plugin
    jenkins_plugin:  
      name: pipeline
      url_username: "host_user"
      url_password: "host_pwd"
      url: "host_url"
     
  - name: Check if restart is required by any of the versioned plugins
    set_fact:
      jenkins_restart_required: yes

  - name: Restart Jenkins if required
    service:
      name: jenkins
      state: restarted
    when: jenkins_restart_required
