
# Example of how to authenticate
---
- hosts: localhost

  tasks:
  - name: Install plugin
    jenkins_plugin:
      name: CCM
      #state: present
      url_username: admin
      url_password: password
      url: http://localhost:8080
