
# Example of how to authenticate
---
- hosts: localhost

  tasks:
  - uri:
      url: 'http://127.0.0.1:8080/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)'
      user: admin
      password: password
      force_basic_auth: yes
      return_content: yes
    register: crumb
  
  - debug:
      msg: "{{ crumb.content.split(':')[1] }}"

  - uri:
      method: POST
      url: 'http://127.0.0.1:8080/credentials/store/system/domain/_/createCredentials'
      user: admin
      password: password
      force_basic_auth: yes
      follow_redirects: all
      headers:
        Jenkins-Crumb: "{{ crumb.content.split(':')[1] }}"
      body: |
        json={
          "": "0",
          "credentials": {
            "scope": "GLOBAL",
            "id": "credential_id_here2",
            "username": "username_here2",
            "password": "password_here2",
            "description": "My new credentials2",
            "$class": "com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl"
          }
        }
