---
- hosts: localhost

  tasks:
  - name: interacting with an untrusted HTTPS connection
    jenkins_script:
      script: 'println(Jenkins.instance.pluginManager.plugins)'
      user: admin
      password: password
      url: http://localhost:8080
      validate_certs: no
