---
- hosts: localhost

  tasks:
  - uri:
      url: 'http://localhost:8080/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)'
      user: "admin"
      password: "password"
      force_basic_auth: yes
      return_content: yes
    register: crumb

  - debug:
      msg: "{{ crumb.content.split(':')[1] }}"

  - uri:
      method: POST
      url: 'http://localhost:8080/credentials/store/system/domain/_/createCredentials'
      user: "admin"
      password: "password"
      force_basic_auth: yes
      follow_redirects: all
      headers:
        Jenkins-Crumb: "{{ crumb.content.split(':')[1] }}"
      body: |
        json={
          "": "0",
          "credentials": {
            "scope": "GLOBAL",
            "id": "cred_id_det1",
            "username": "cred_usr_det1",
            "password": "cred_pwd_det1",
            "description": "cred_id_det1",
            "$class": "com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl"
          }
        }
